### ISSUE TITLE
I knew someone would start this project!

### ISSUE THREAD

**Issue by Brisklemonade** [CollierCZ/markdoc-svelte#1]
Awesome to see you tackle this, if you would like contributions I would love to help you.

**Comment by CollierCZ** [comment]
I'd definitely be happy for any contributions. I'm no expert in the field and it may take me a while to get to the place I was hoping with it on my own.

**Comment by Brisklemonade** [comment]
This would definitely be useful for a project I'm going to start. Do you by chance use Discord?

**Comment by CollierCZ** [comment]
I haven't used it often. But I'm open to trying new things (as I think this repository makes clear :grin:).

**Comment by Brisklemonade** [comment]
That's wonderful, because I would like to discuss things with you further; discord makes that really easy.

You can either add me directly by entering this username: Brisklemonade#6276

Or you can join my [Discord community](https://discord.gg/2J2xmzCS79). It's filled with svelte devs, so you may even be able to have more assistance!

**Comment by CollierCZ** [comment]
I tried joining, but Discord does not like me and immediately disabled my account. :disappointed: Will see if I can get a response on that.

**Comment by Brisklemonade** [comment]
Oh wow that's unfortunate. In the meantime, what do you need help with right now? Any specific issues to tackle or features to implement?

**Comment by Brisklemonade** [comment]
Just let me know so I can help you work on it!

**Comment by CollierCZ** [comment]
This week I'm hoping to finish the basic features that are in the Readme (the parts of the schema). I have some tests as I go, but they might be only for my particular situation. If you have ideas about how it could work elsewhere, that'd be great.

Or any ideas about what definitely needs to be included. Even a review of the code if it's a reasonable approach would be greatly appreciated
