### ISSUE TITLE
Blank Layout

### ISSUE THREAD

**Issue by realsama** [CollierCZ/markdoc-svelte#8]
Hello, thanks for this library.

I have tried following the guide in the readme but I have been unable to replicate it. What I get is a blank layout file which means that the props are not getting sent. The below is my setup. Any help appreciated.

```
page.md
---
title: Using the Next.js plugin
description: Integrate Markdoc into your Next.js app
---

# {% $frontmatter.title %}

# {% $frontmatter.description %}
```

```
+layout.svelte
<script lang="ts">
  export let title = ''
</script>

<h1>{title}</h1>

<slot />
```

```
svelte.config.js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { markdoc } from "markdoc-svelte";


/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter()
	},
	extensions: ['.svelte', '.markdoc', ".md"],
	preprocess: [
		markdoc({
			layout: "./src/rosutes/layout.svelte",
			extensions: [".markdoc", ".md"],
		}),
		vitePreprocess(),
	],
};

export default config;
```

**Comment by CollierCZ** [comment]
Hi, @shepherd1530. Sorry I've been away for a while. Did you get this sorted?

**Comment by shepherd1530** [comment]
@CollierCZ Yes, I have sorted it. Although I am facing two different issues now. Can I open a different issue or can you assist here? Thanks.

**Comment by CollierCZ** [comment]
Feel free to open a new one or write here. I haven't got this in the state I wanted, but happy to try to help.
